export const tutorialSteps = [
  { mode: 'micro', title: 'Orbit the city', body: 'Left-drag to orbit around the model.', requirement: 'camera-manual', auto: true, action: 'Orbit the camera to continue.' },
  { mode: 'micro', title: 'Pan and zoom', body: 'Right-drag to pan and use the wheel or trackpad to zoom.', action: 'Practice panning and zooming, then continue.' },
  { mode: 'micro', title: 'Use movement and presets', body: 'WASD moves through the city. Default, Street, and Top provide repeatable views.', requirement: 'camera-preset', auto: true, action: 'Choose a camera preset.' },
  { mode: 'micro', title: 'Move this panel', body: 'Drag the full header on desktop. On mobile, pull the bottom sheet between its three positions.', requirement: 'move-panel', auto: true, action: 'Move this panel.' },
  { mode: 'micro', title: 'Select a building', body: 'Buildings explain purpose, capacity, residents, and current occupancy.', requirement: 'building', auto: true, action: 'Select a building.' },
  { mode: 'micro', title: 'Read and close building details', body: 'Homes distinguish residents from people currently present. Other places list current users.', requirement: 'close-building', auto: true, action: 'Close the building panel.' },
  { mode: 'micro', title: 'Select an agent', body: 'Choose a person on the street or a colored billboard circle in an occupancy tower.', requirement: 'agent', auto: true, action: 'Select an agent.' },
  { mode: 'micro', title: 'Read and close agent details', body: 'The panel explains activity, alcohol stage, health, cash, location, BAC, and simplified neurotransmitters.', requirement: 'close-agent', auto: true, action: 'Close the agent panel.' },
  { mode: 'micro', title: 'Use the Agent Directory', body: 'The directory finds, highlights, follows, and opens details for any generated person.', requirement: 'directory', auto: true, action: 'Open the Agent Directory.' },
  { mode: 'micro', title: 'Play and pause', body: 'Playback advances continuously between two-hour decision boundaries.', requirement: 'play', auto: true, action: 'Press Play.' },
  { mode: 'micro', title: 'Pause playback', body: 'Pause whenever you want to inspect a stable moment.', requirement: 'pause', auto: true, action: 'Pause playback.' },
  { mode: 'micro', title: 'Two days at 128×', body: 'Press 128× to run two live days from the Default camera. The display will count back before restoring this exact snapshot.', requirement: 'speed-demo', auto: true, action: 'Press 128× and watch the restoration.' },
  { mode: 'micro', title: 'Switch to Meso', body: 'Meso reveals social and location relationships.', requirement: 'meso', auto: true, action: 'Switch to Meso.' },
  { mode: 'meso', title: 'Select an agent network', body: 'Select an agent or tower circle to create its labeled Network hub.', requirement: 'meso-agent', auto: true, action: 'Select an agent.' },
  { mode: 'meso', title: 'Split the network hub', body: 'Select Network to reveal Social and Locations categories.', requirement: 'network-all', auto: true, action: 'Select the Network hub.' },
  { mode: 'meso', title: 'Inspect Social', body: 'Social highlights relationship edges and the matching detail-panel section.', requirement: 'network-social', auto: true, action: 'Select Social.' },
  { mode: 'meso', title: 'Inspect Locations', body: 'Locations highlights home, workplace, gathering, and current-place links.', requirement: 'network-locations', auto: true, action: 'Select Locations.' },
  { mode: 'meso', title: 'Building users', body: 'Selecting a building creates one Users node. Building networks do not split.', requirement: 'meso-building', auto: true, action: 'Select a building.' },
  { mode: 'meso', title: 'Switch to Macro', body: 'Macro shifts from individual relationships to aggregate outcomes and policy levers.', requirement: 'macro', auto: true, action: 'Switch to Macro.' },
  { mode: 'macro', title: 'Review controls and outcomes', body: 'Macro combines policy controls with rolling outcomes and structured history.', action: 'Review the controls and outcomes, then continue.' },
  { mode: 'macro', title: 'Review graphs and timescales', body: 'Charts show two-hour samples across 24-hour, 7-day, and 30-day windows.', action: 'Review graph timescales, then continue.' },
  { mode: 'macro', title: 'Apply a policy', body: 'Applied policy changes enter the simulation at the next two-hour decision boundary.', requirement: 'policy', auto: true, highlight: 'alcoholPrice', action: 'Apply a policy.' },
  { mode: 'macro', title: 'Open settings', body: 'Settings contains interface size, restart controls, version information, and the model-interface disclaimer.', requirement: 'settings', auto: true, action: 'Open settings.' },
  { mode: 'macro', title: 'Finish with help', body: 'Help summarizes camera controls and the purpose of Micro, Meso, and Macro.', requirement: 'help', auto: true, action: 'Open Help to finish.' },
]
