export const tutorialSteps = [
  { mode: 'micro', title: 'Move through the city', body: 'Orbit, pan, zoom, or choose a camera preset. Camera movement helps connect model activity to place.', requirement: 'camera', auto: true, action: 'Move the camera to continue.' },
  { mode: 'micro', title: 'Move this panel', body: 'Desktop panels can be dragged from their header. On mobile they behave as snapping bottom sheets.', requirement: 'move-panel', auto: true, action: 'Move the tutorial panel to continue.' },
  { mode: 'micro', title: 'Select a building', body: 'Buildings explain purpose, capacity, residents, and current occupancy. Occupancy spheres represent people currently inside.', requirement: 'building', auto: true, action: 'Select a building to continue.' },
  { mode: 'micro', title: 'Read building details', body: 'Homes list residents and whether they are present. Other places list their current occupants.', action: 'Review the panel, then continue.' },
  { mode: 'micro', title: 'Close the building panel', body: 'Closing a detail panel clears its selection and map highlight.', requirement: 'close-panel', auto: true, action: 'Close the building panel.' },
  { mode: 'micro', title: 'Select an agent', body: 'Choose a visible person or a colored occupancy sphere.', requirement: 'agent', auto: true, action: 'Select an agent to continue.' },
  { mode: 'micro', title: 'Read individual details', body: 'The individual panel explains activity, alcohol stage, health, cash, location, BAC, and simplified neurotransmitter state.', action: 'Review the panel, then continue.' },
  { mode: 'micro', title: 'Play and pause', body: 'Playback advances the model continuously between two-hour decision boundaries.', requirement: 'play', auto: true, action: 'Press Play to continue.' },
  { mode: 'micro', title: 'Pause playback', body: 'Pause whenever you want to inspect a moment without the city changing beneath you.', requirement: 'pause', auto: true, action: 'Pause the simulation.' },
  { mode: 'micro', title: 'Two days at 64×', body: 'The model will run through two day/night cycles, then visually rewind and restore this exact snapshot.', requirement: 'speed-demo', auto: true, action: 'Watch the live cycle and rewind.' },
  { mode: 'micro', title: 'Switch to Meso', body: 'Meso reveals social and location relationships around the selected person.', requirement: 'meso', auto: true, action: 'Switch to Meso.' },
  { mode: 'meso', title: 'Explore the network hub', body: 'Select the central hub to separate Social and Locations relationships. Selecting a category highlights its edges.', highlight: 'friends', action: 'Explore the hub, then continue.' },
  { mode: 'meso', title: 'Switch to Macro', body: 'Macro shifts from individual relationships to aggregate outcomes and policy levers.', requirement: 'macro', auto: true, action: 'Switch to Macro.' },
  { mode: 'macro', title: 'Apply a policy', body: 'Change a policy lever and apply it. Policies enter the simulation at the next two-hour boundary.', requirement: 'policy', auto: true, highlight: 'alcoholPrice', action: 'Apply a policy to continue.' },
  { mode: 'macro', title: 'Open settings', body: 'Settings contains UI scale, restart controls, version information, and the model-interface disclaimer.', requirement: 'settings', auto: true, action: 'Open settings.' },
  { mode: 'macro', title: 'Finish with help', body: 'The help panel summarizes camera controls and the purpose of Micro, Meso, and Macro.', requirement: 'help', auto: true, action: 'Close settings and open Help to finish.' },
]
